### ISSUE TITLE
As of version 0.1.4, custom nether ores generate in the overworld.

### ISSUE THREAD

**Issue by Munsterlandr** [Filostorm/Multiblock-Madness-2#3]
When I load up a new world, there's a bunch of what looks to be nether custom ore veins just strewn about. some biomes seem to be free of it, but most are not. I saw this issue in version 0.1.3 as well.

Pictures:
![From v0.1.4 directly](https://user-images.githubusercontent.com/81447509/223290107-4a69f0c8-a4d4-4947-a2b7-c297dd614eaf.png)
![Taken in version 0.1.3](https://user-images.githubusercontent.com/81447509/223290179-9ad54cc6-70b6-4c70-91bd-de7c0291dada.png)

**Comment by Filostorm** [comment]
The cause of that issue is when the ore generation script can't find the blocks its supposed to replace. In this case it looks like it can't find netherrack redstone ore and either gold or tin.

Would you mind commenting out this line: [event.hide(/excavated_variants:*/)](https://github.com/Filostorm/Multiblock-Madness-2/blob/cd9fb2b33ac4e645d6af0f517a9149ed50172982/kubejs/client_scripts/rei.js#L35) and checking for what redstone ores there are in REI?

**Comment by Filostorm** [comment]
This doesn't happen on my end, but you aren't the first to have the issue

**Comment by Filostorm** [comment]
Well, I'm able to fix that issue, but the root cause will still exist, which is missing ores
